extends: airbnb/base
parser: babel-eslint
plugins:
  - mocha
  - flowtype
rules:
  mocha/no-exclusive-tests: 2
  flowtype/require-valid-file-annotation: 2

  no-else-return: 0
  max-len: 0
  new-cap: 0
  consistent-return: 0
  prefer-const: 0
  comma-dangle: 0
  no-param-reassign: 0

  no-underscore-dangle: 0
  no-prototype-builtins: 0
  import/no-extraneous-dependencies: 0
  class-methods-use-this: 0
  no-await-in-loop: 0
  no-multi-assign: 0
  arrow-parens: [2, "as-needed"]
  operator-linebreak: ["error", "after"]
  no-mixed-operators: 0
