#!/bin/bash

echo $1

googleminify=$1

if [ -z "$googleminify" ]; then googleminify="/opt/minify/compiler.jar"; fi

echo -e "  "
echo -e "  USING: $googleminify TO MINIFY..."
echo -e "  COMPILING PUBNUB JAVASCRIPT API..."

cat ./json.js ./websocket.js ./pubnub.js > ./pubnub.tmp
echo "(function(){" > ./pubnub.min.js
java -jar $googleminify --js=./pubnub.tmp --compilation_level=ADVANCED_OPTIMIZATIONS >> ./pubnub.min.js
echo "})();" >> ./pubnub.min.js

echo -e "  >>COMPRESSING<< PUBNUB JAVASCRIPT API..."
cat ./pubnub.min.js | gzip -c9 > ./pubnub.min.js.gz

rm ./pubnub.tmp
echo -e "  "
echo -e "  DONE!\n"
