/* @flow */

export default {
  subscribeKey: 'string',
  publishKey: 'string',
  cipherKey: 'string',
  authKey: 'string',
  secretKey: 'string',
  logVerbosity: 'boolean',
  uuid: 'string',
  ssl: 'boolean',
  origin: 'string',
  presenceTimeout: 'number',
  heartbeatInterval: 'number',
  restore: 'boolean',
  keepAlive: 'boolean',
  keepAliveSettings: 'object',
  useInstanceId: 'boolean',
  sdkFamily: '*ignore',
  networking: '*ignore',
  db: '*ignore',
  customDecrypt: 'function',
  customEncrypt: 'function',
  partnerId: '*ignore',
  autoNetworkDetection: '*ignore',
  announceSuccessfulHeartbeats: '*ignore',
  requestMessageCountThreshold: '*ignore',
  filterExpression: '*ignore',
  removeAllListeners: '*ignore'
};
