var StatusCategory;
(function (StatusCategory) {
    StatusCategory["PNNetworkIssuesCategory"] = "PNNetworkIssuesCategory";
    StatusCategory["PNTimeoutCategory"] = "PNTimeoutCategory";
    StatusCategory["PNCancelledCategory"] = "PNCancelledCategory";
    StatusCategory["PNBadRequestCategory"] = "PNBadRequestCategory";
    StatusCategory["PNAccessDeniedCategory"] = "PNAccessDeniedCategory";
    StatusCategory["PNValidationErrorCategory"] = "PNValidationErrorCategory";
    StatusCategory["PNAcknowledgmentCategory"] = "PNAcknowledgmentCategory";
    StatusCategory["PNUnknownCategory"] = "PNUnknownCategory";
    StatusCategory["PNNetworkUpCategory"] = "PNNetworkUpCategory";
    StatusCategory["PNNetworkDownCategory"] = "PNNetworkDownCategory";
    StatusCategory["PNReconnectedCategory"] = "PNReconnectedCategory";
    StatusCategory["PNConnectedCategory"] = "PNConnectedCategory";
    StatusCategory["PNRequestMessageCountExceededCategory"] = "PNRequestMessageCountExceededCategory";
    StatusCategory["PNDisconnectedCategory"] = "PNDisconnectedCategory";
    StatusCategory["PNConnectionErrorCategory"] = "PNConnectionErrorCategory";
    StatusCategory["PNDisconnectedUnexpectedlyCategory"] = "PNDisconnectedUnexpectedlyCategory";
})(StatusCategory || (StatusCategory = {}));
export default StatusCategory;
