name: "Frogbot Scan Repository"
on:
  workflow_dispatch:
  schedule:
    # The repository will be scanned once a day at 00:00 GMT.
    - cron: "0 0 * * *"
permissions:
  contents: write
  pull-requests: write
  security-events: write
jobs:
  scan-repository:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # The repository scanning will be triggered periodically on the following branches.
        branch: ["master"]
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - uses: jfrog/frogbot@v2
        env:
          JF_URL: ${{ secrets.JF_URL }}
          JF_ACCESS_TOKEN: ${{ secrets.JF_ACCESS_TOKEN }}
          JF_GIT_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          JF_GIT_BASE_BRANCH: ${{ matrix.branch }}
          JF_PATH_EXCLUSIONS: "*git*;*node_modules*;*target*;*venv*;*test*;*karma*;*dist*;*lib*"
          JF_MIN_SEVERITY: "Medium"
          JF_GIT_EMAIL_AUTHOR: "120067856+pubnub-release-bot@users.noreply.github.com"
          JF_ALLOWED_LICENSES: "MIT, Apache-2.0"
          # JF_BRANCH_NAME_TEMPLATE: "frogbot-{IMPACTED_PACKAGE}-{BRANCH_NAME_HASH}"
          # JF_COMMIT_MESSAGE_TEMPLATE: "Upgrade {IMPACTED_PACKAGE} to {FIX_VERSION}"
          # JF_PULL_REQUEST_TITLE_TEMPLATE: "[🐸 Frogbot] Upgrade {IMPACTED_PACKAGE} to {FIX_VERSION}"
          # JF_AVOID_EXTRA_MESSAGES: "TRUE"
          # JF_PR_COMMENT_TITLE: ""